<?php require('template/header.phtml') ?>
<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">


<div>
    <header id="hero" class="hero">
        <div class="flex-containerOne w-container">
            <div class="feature-image-mask"><img src="images/University/campus4 (Medium).jpg" height="400" width="400"></div>
            <div class="feature-image">
                <h2>University Students</h2>
                <p>How are you preparing your computer science students for the IT workplace? Smooth their journey into the industry by providing them with BCS Student membership.</p>
                <p>Membership connects your undergraduates with the tech industry... and maybe a future employer or two

                    Students can tap into experience straight from the IT community by matching with a BCS mentor

                    Interactive career tools include CV writer, interview simulator, personal assessments and e-learning

                    Your graduate outcomes improve, as students take control of their own employability



                    Provide your annual computer science intake with BCS membership for as little as £15 per student, per year</p>
            </div>
        </div>
    </header>
</div>
<div>
    <header id="hero2" class="hero2">
        <div class="flex-containerTwo w-container">
            <div>
                <h1>Test2</h1>
                <p>Test2 Test2 Test2</p>
            </div>
            <div class="hero-image-mask"><img src="images/bcs-logo.svg"></div>
        </div>
    </header>
</div>


<?php require('template/footer.phtml') ?>


