<?php require('template/header.phtml') ?>


<form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
<div id="title">
    <h2><b><u>Universities</u></b></h2>
</div>
    <div id="uni">
    <div id="universities">
        <div id="universitiesRow"><img src="images/bcs-logo.svg"></div>
        <div id="universitiesColumn">
        <h3><u>Salford</u></h3>
        <p>test test test</p>
        </div>
    </div>

    <div id="universities">
    <div id="universitiesRow"><img src="images/bcs-logo.svg"></div>
    <div id="universitiesColumn">
        <h3><u>Salford</u></h3>
        <p>test test test</p>
    </div>
    </div>

    <div id="universities">
        <div id="universitiesRow"><img src="images/bcs-logo.svg"></div>
        <div id="universitiesColumn">
            <h3><u>Salford</u></h3>
            <p>test test test</p>
        </div>
    </div>

    <div id="universities">
        <div id="universitiesRow"><img src="images/bcs-logo.svg"></div>
        <div id="universitiesColumn">
            <h3><u>Salford</u></h3>
            <p>test test test</p>
        </div>
    </div>

    <div id="universities">
        <div id="universitiesRow"><img src="images/bcs-logo.svg"></div>
        <div id="universitiesColumn">
            <h3><u>Salford</u></h3>
            <p>test test test</p>
        </div>
    </div>
    </div>
</form>

<?php require('template/footer.phtml') ?>
