<?php require('template/header.phtml') ?>

<div id="myprofile">
    <h1><b>My Profile</b></h1>
    <p></p>
    <h2><b><u>Welcome <?php
                echo $_SESSION['name'];
                ?>!</u></b></h2>
    <p></p>
    <label>Name</label>
    <?php echo $view->sessionName; ?>
    <br>
    <label>Email</label>
    <?php echo $view->sessionEmail; ?>
    <br>
    <label>Date of Birth</label>
    <?php echo $view->sessionDob; ?>
    <br>
    <label>Type</label>
    <?php echo $view->sessionType; ?>
    <br>
    <label>Phone Number</label>
    <?php echo $view->sessionPhonenumber; ?>
    <br>
    <label>Address1</label>
    <?php echo $view->sessionAddress1; ?>
    <br>
    <label>Address2</label>
    <?php echo $view->sessionAddress2; ?>
    <br>
    <label>Address3</label>
    <?php echo $view->sessionAddress3; ?>
    <br>
    <label>Postcode</label>
    <?php echo $view->sessionPostcode; ?>

</div>

<?php echo '<div id="myprofileextra" style=" ' . $view->display . '">'; ?>
    <h2>More details:</h2>

    <form action="<?php echo $_SERVER['PHP_SELF'] . '?id=student'; ?>" method="post" enctype="multipart/form-data">
        <label>University: </label>
        <input type="text" name="university" value=""
            <?php if (isset($_POST['university'])) {
                echo $_POST['university']; 	} ?> />
        <br>
        <label>Course: </label>
        <input type="text" name="course" value=""
            <?php if (isset($_POST['course'])) {
                echo $_POST['course']; 	} ?> />
        <br>
        <label>Skills: </label>
        <select id="" name="skills" <?php if (isset($_POST['skills'])) { echo $_POST['skills']; 	} ?> />
        <option value="" name="skills"> </option>
        <?php
        require_once ('Models/SkillsDataSet.php');
        $skillDataSet = new SkillsDataSet();
        $view->skillDataSet = $skillDataSet->fetchAllskills();
        foreach ($view->skillDataSet as $skillData) {
            echo '<option value="' . $skillData->getSkillsId() . '" name="skills">' . $skillData->getSkillName() . '</option>';
        }
        ?>
        </select>
        <br>
        <label>CV Upload: </label>
        <input type="file" name="file"
            <?php if (isset($_POST['file'])) {
            echo $_POST['file']; 	} ?>/>
        <?php if (isset($view->uploadresult)) : ?>
            <p><?php echo $view->uploadresult; ?></p>
        <?php endif; ?>
        <input type="submit" name="fileSubmit"/>


            <div id="loginbutton">
            <input type="submit" value="submit" name="submit" />
            <input type="reset" value="reset" name="reset" />

            <?php if (isset($view->result)) : ?>
            <p><?php echo $view->result; ?></p>
            <?php endif; ?>
            </div>
    </form>
</div>
<?php echo '<div id="myprofileextra" style=" ' . $view->displayOpp . '">'; ?>
    <h2>More details:</h2>
        <label>University: </label>
        <?php echo $view->sessionUniversity; ?>
        <br>
        <label>Course: </label>
        <?php echo $view->sessionCourse; ?>
        <br>
        <label>Skills: </label>
        <?php echo $view->sessionSkills; ?>
        <br>
        <label>CV Upload: </label>
        <?php echo file_get_contents('cvuploads/' . $view->sessionFile); ?>
        <br>

</div>
<?php require('template/footer.phtml') ?>
