<?php require('template/header.phtml') ?>


<form action="mailto:j.a.hodgson@edu.salford.ac.uk" method="post">
<div id="title">
    <h2><b><u>Support</u></b></h2>
</div>
<div id="support">
    <p>







    </p>

</div>
    <div id="contactus">
        <label>Email: </label>
        <input type="text" name="email" value=""/>
        <label>Details: </label>
        <input type="text" name="details" value=""/>
        <input type="submit" value="Contact Us"/>
        <input type="reset" value="Reset">
    </div>

<?php require('template/footer.phtml') ?>
