<html>
<footer id="footer" class="footer">
       <div class="container w-container">
           <div class="footer-flex-container">
               <div>
                   <ul role="list" class="w-list-unstyled">
                       <li>
                           <a href="support.php" class="footer-link">Support</a>
                       </li>
                   </ul>
               </div>
               <div>
                   <ul role="list" class="w-list-unstyled">
                       <li>
                           <a href="aboutus.php" class="footer-link">About Us</a>
                       </li>
                   </ul>
               </div>
               <div>
                   <ul role="list" class="w-list-unstyled">
                       <li>
                           <a href="legal.php" class="footer-link">Legal and Privacy</a>
                       </li>
                   </ul>
               </div>
           </div>
           <div  class="footer-heading">Copyright 2021 BCS. All rights reserved.</div>
       </div>
   </footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</html>